import React from "react";

function Section5SVG() {
  return (
    <svg className="relative z-1" viewBox="0 0 1440 1150">
      <path
        id="topLeftLine"
        fill="none"
        stroke="#584E93"
        strokeDasharray="none"
        strokeDashoffset="0"
        strokeOpacity="0.37"
        strokeWidth="2"
        d="M534.5 539H380V398H0"
        opacity="0.8"
      ></path>
      <path
        id="topRightLine"
        fill="none"
        stroke="#584E93"
        strokeDasharray="none"
        strokeDashoffset="0"
        strokeOpacity="0.8"
        strokeWidth="2"
        d="M893 537h93v-63h454"
        opacity="0.3"
      ></path>
      <path
        id="bottomRightLine"
        fill="none"
        stroke="#584E93"
        strokeDasharray="none"
        strokeDashoffset="0"
        strokeOpacity="0.37"
        strokeWidth="2"
        d="M955.5 594h483"
      ></path>
      <path
        id="bottomLeftLine"
        fill="none"
        stroke="#584E93"
        strokeDasharray="none"
        strokeDashoffset="0"
        strokeOpacity="0.37"
        strokeWidth="2"
        d="M485 616.5H285v57H-3.5"
        opacity="0.5"
      ></path>
      <g
        id="topRightLineGlow"
        className="line-glow"
        filter="url(#automation_filter0_f)"
        opacity="0.2"
        style={{ mixBlendMode: "color-dodge" }}
      >
        <g filter="url(#automation_filter1_f)">
          <ellipse
            cx="1279.5"
            cy="474.5"
            fill="#B095FF"
            rx="175.5"
            ry="0.5"
            transform="rotate(-180 1279.5 474.5)"
          ></ellipse>
        </g>
        <g filter="url(#automation_filter2_f)">
          <ellipse
            cx="1279.5"
            cy="474.5"
            fill="#9E7CFF"
            rx="97.5"
            ry="0.278"
            transform="rotate(-180 1279.5 474.5)"
          ></ellipse>
        </g>
      </g>
      <g
        id="bottomRightLineGlow"
        className="line-glow"
        filter="url(#automation_filter3_f)"
        opacity="0.2"
        style={{ mixBlendMode: "color-dodge" }}
      >
        <g filter="url(#automation_filter4_f)">
          <ellipse
            cx="1135"
            cy="594.5"
            fill="#B095FF"
            rx="157"
            ry="1.5"
            transform="rotate(-180 1135 594.5)"
          ></ellipse>
        </g>
        <g filter="url(#automation_filter5_f)">
          <ellipse
            cx="1135"
            cy="594.5"
            fill="#9E7CFF"
            rx="87.222"
            ry="0.833"
            transform="rotate(-180 1135 594.5)"
          ></ellipse>
        </g>
      </g>
      <g id="bottomLeftLineGlowOne" className="line-glow" opacity="0.5">
        <g
          filter="url(#automation_filter9_f)"
          opacity="0.2"
          style={{ mixBlendMode: "color-dodge" }}
        >
          <g filter="url(#automation_filter10_f)">
            <ellipse
              cx="285.5"
              cy="634"
              fill="#B095FF"
              rx="26"
              ry="1.5"
              transform="rotate(-90 285.5 634)"
            ></ellipse>
          </g>
          <g filter="url(#automation_filter11_f)">
            <ellipse
              cx="285.5"
              cy="634"
              fill="#9E7CFF"
              rx="14.444"
              ry="0.833"
              transform="rotate(-90 285.5 634)"
            ></ellipse>
          </g>
        </g>
        <g
          filter="url(#automation_filter12_f)"
          opacity="0.2"
          style={{ mixBlendMode: "color-dodge" }}
        >
          <g filter="url(#automation_filter13_f)">
            <ellipse
              cx="292.5"
              cy="616.5"
              fill="#B095FF"
              rx="23.5"
              ry="1.5"
            ></ellipse>
          </g>
          <g filter="url(#automation_filter14_f)">
            <ellipse
              cx="292.5"
              cy="616.5"
              fill="#9E7CFF"
              rx="13.056"
              ry="0.833"
            ></ellipse>
          </g>
        </g>
      </g>
      <g
        id="bottomLeftLineGlowTwo"
        className="line-glow"
        filter="url(#automation_filter6_f)"
        opacity="0.2"
        style={{ mixBlendMode: "color-dodge" }}
      >
        <g filter="url(#automation_filter7_f)">
          <ellipse
            cx="57"
            cy="673.5"
            fill="#B095FF"
            rx="48"
            ry="0.5"
            transform="rotate(-180 57 673.5)"
          ></ellipse>
        </g>
        <g filter="url(#automation_filter8_f)">
          <ellipse
            cx="57"
            cy="673.5"
            fill="#9E7CFF"
            rx="26.667"
            ry="0.278"
            transform="rotate(-180 57 673.5)"
          ></ellipse>
        </g>
      </g>
      <g className="line-glow" opacity="0.5">
        <g
          filter="url(#automation_filter15_f)"
          opacity="0.2"
          style={{ mixBlendMode: "color-dodge" }}
        >
          <g filter="url(#automation_filter16_f)">
            <ellipse
              cx="450.5"
              cy="539.5"
              fill="#B095FF"
              rx="72.5"
              ry="1.5"
              transform="rotate(180 450.5 539.5)"
            ></ellipse>
          </g>
          <g filter="url(#automation_filter17_f)">
            <ellipse
              cx="450.5"
              cy="539.5"
              fill="#9E7CFF"
              rx="40.278"
              ry="0.833"
              transform="rotate(180 450.5 539.5)"
            ></ellipse>
          </g>
        </g>
        <g
          filter="url(#automation_filter18_f)"
          opacity="0.1"
          style={{ mixBlendMode: "color-dodge" }}
        >
          <g filter="url(#automation_filter19_f)">
            <ellipse
              cx="381.5"
              cy="510"
              fill="#B095FF"
              rx="29"
              ry="1.5"
              transform="rotate(-90 381.5 510)"
            ></ellipse>
          </g>
          <g filter="url(#automation_filter20_f)">
            <ellipse
              cx="381.5"
              cy="510"
              fill="#9E7CFF"
              rx="16.111"
              ry="0.833"
              transform="rotate(-90 381.5 510)"
            ></ellipse>
          </g>
        </g>
      </g>
      <path
        fill="#352B73"
        stroke="#584E93"
        strokeWidth="2"
        d="M-0.179 0.579H19.687V20.445H-0.179z"
        className="automation-float-sq"
        opacity="0.2"
        transform="matrix(.82095 .571 -.99997 .00751 987.412 419.676)"
      ></path>
      <g className="automation-float-sq" opacity="0.7">
        <path
          fill="url(#automation_paint0_linear)"
          stroke="#584E93"
          strokeWidth="2"
          d="M-0.447 -0.408H46.592V46.631H-0.447z"
          opacity="0.2"
          transform="matrix(-.86603 .5 .41866 -.90814 983.805 756.98)"
        ></path>
        <path
          fill="none"
          stroke="url(#automation_paint1_radial)"
          d="M949.643 765.355l13.375-27.515 17.197-9.936"
          opacity="0.3"
        ></path>
        <g filter="url(#automation_filter21_f)" opacity="0.03">
          <path
            fill="#F48DFD"
            d="M961.931 750.442l13.245-18.789 9.681-3.378-10.323 13.707 4.321-2.203-14.459 29.049-10.931 4.135 15.287-26.237-6.821 3.716z"
          ></path>
        </g>
      </g>
      <g className="automation-float-sq">
        <path
          fill="url(#automation_paint2_linear)"
          stroke="#584E93"
          strokeWidth="2"
          d="M0.535 -0.285H53.065V52.245000000000005H0.535z"
          opacity="0.2"
          transform="matrix(-.18072 -.98353 .71523 .69889 543.175 737.072)"
        ></path>
        <path
          fill="none"
          stroke="url(#automation_paint3_radial)"
          d="M533.264 683.601l37.705 37.9 3.999 21.72"
          opacity="0.3"
        ></path>
        <g filter="url(#automation_filter22_f)" opacity="0.03">
          <path
            fill="#F48DFD"
            d="M562.758 722.147l13.476 24.561-1.386 11.601-9.486-18.568.136 5.604-23.977-32.05L542.739 700l20.493 31.14-.474-8.993z"
          ></path>
        </g>
      </g>
      <g className="automation-float-sq">
        <path
          fill="url(#automation_paint4_linear)"
          stroke="#584E93"
          strokeWidth="2"
          d="M0.326 0.51H88.725V88.909H0.326z"
          opacity="0.2"
          transform="matrix(.96593 -.25882 -.63944 .76884 523.142 413.657)"
        ></path>
        <path
          fill="none"
          stroke="url(#automation_paint5_radial)"
          d="M609.233 391.423l-57.63 67.334-35.361 9.487"
          opacity="0.3"
        ></path>
        <g filter="url(#automation_filter23_f)" opacity="0.03">
          <path
            fill="#F48DFD"
            d="M559.553 436.838l-32.549 27.136-18.85 1.395 24.921-19.48-8.745 1.861 39.606-44.827 21.437-2.147-39.738 39.425 13.918-3.363z"
          ></path>
        </g>
      </g>
      <g id="automationMainGlow" style={{ mixBlendMode: "color-dodge" }}>
        <g filter="url(#automation_filter33_f)">
          <circle cx="716.5" cy="574.501" r="191.5" fill="#B095FF"></circle>
        </g>
        <g filter="url(#automation_filter34_f)">
          <circle cx="716.501" cy="574.502" r="106.389" fill="#9E7CFF"></circle>
        </g>
        <g filter="url(#automation_filter35_f)">
          <circle cx="716.502" cy="574.503" r="21.278" fill="#fff"></circle>
        </g>
      </g>
      <defs>
        <filter
          id="automation_filter0_f"
          width="361"
          height="11"
          x="1099"
          y="469"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter1_f"
          width="377"
          height="27"
          x="1091"
          y="461"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter2_f"
          width="201"
          height="6.556"
          x="1179"
          y="471.222"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter3_f"
          width="324"
          height="13"
          x="973"
          y="588"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter4_f"
          width="340"
          height="29"
          x="965"
          y="580"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter5_f"
          width="180.444"
          height="7.667"
          x="1044.78"
          y="590.667"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter6_f"
          width="106"
          height="11"
          x="4"
          y="668"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter7_f"
          width="122"
          height="27"
          x="-4"
          y="660"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter8_f"
          width="59.333"
          height="6.556"
          x="27.333"
          y="670.222"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter9_f"
          width="13"
          height="62"
          x="279"
          y="603"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter10_f"
          width="29"
          height="78"
          x="271"
          y="595"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter11_f"
          width="7.667"
          height="34.889"
          x="281.667"
          y="616.555"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter12_f"
          width="57"
          height="13"
          x="264"
          y="610"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter13_f"
          width="73"
          height="29"
          x="256"
          y="602"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter14_f"
          width="32.111"
          height="7.667"
          x="276.445"
          y="612.667"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter15_f"
          width="155"
          height="13"
          x="373"
          y="533"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter16_f"
          width="171"
          height="29"
          x="365"
          y="525"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter17_f"
          width="86.556"
          height="7.667"
          x="407.222"
          y="535.667"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter18_f"
          width="13"
          height="68"
          x="375"
          y="476"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter19_f"
          width="29"
          height="84"
          x="367"
          y="468"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter20_f"
          width="7.667"
          height="38.222"
          x="377.667"
          y="490.889"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter21_f"
          width="41.393"
          height="60.781"
          x="948.465"
          y="720.229"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter22_f"
          width="75.587"
          height="68.309"
          x="521"
          y="695"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter23_f"
          width="87.219"
          height="110.007"
          x="503.154"
          y="378.069"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter24_f"
          width="33"
          height="33"
          x="762"
          y="634.001"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter25_f"
          width="9.889"
          height="9.889"
          x="773.556"
          y="645.557"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter26_f"
          width="4.778"
          height="4.778"
          x="776.111"
          y="648.112"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter27_f"
          width="36"
          height="36"
          x="644"
          y="641.001"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter28_f"
          width="11.556"
          height="11.556"
          x="656.222"
          y="653.223"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter29_f"
          width="5.111"
          height="5.111"
          x="659.444"
          y="656.445"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter30_f"
          width="36"
          height="36"
          x="661"
          y="454.001"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter31_f"
          width="11.556"
          height="11.556"
          x="673.222"
          y="466.223"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter32_f"
          width="5.111"
          height="5.111"
          x="676.444"
          y="469.445"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter33_f"
          width="1149"
          height="1149"
          x="142"
          y="0.001"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="191.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter34_f"
          width="389.547"
          height="389.547"
          x="521.727"
          y="379.729"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="44.192"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter35_f"
          width="160.402"
          height="160.402"
          x="636.301"
          y="494.302"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="29.462"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter36_f"
          width="39"
          height="39"
          x="673"
          y="535"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter37_f"
          width="13.222"
          height="13.222"
          x="685.889"
          y="547.889"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter38_f"
          width="5.444"
          height="5.444"
          x="689.778"
          y="551.778"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter39_f"
          width="195"
          height="195"
          x="623"
          y="433.001"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="32.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter40_f"
          width="66.111"
          height="66.111"
          x="687.444"
          y="497.445"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="7.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter41_f"
          width="27.222"
          height="27.222"
          x="706.889"
          y="516.89"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter42_f"
          width="195"
          height="195"
          x="549"
          y="434.001"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="32.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter43_f"
          width="66.111"
          height="66.111"
          x="613.445"
          y="498.445"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="7.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter44_f"
          width="27.222"
          height="27.222"
          x="632.889"
          y="517.89"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter45_f"
          width="195"
          height="195"
          x="554"
          y="503"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="32.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter46_f"
          width="66.111"
          height="66.111"
          x="618.445"
          y="567.445"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="7.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter47_f"
          width="27.222"
          height="27.222"
          x="637.889"
          y="586.889"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter48_f"
          width="195"
          height="195"
          x="674"
          y="436.001"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="32.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter49_f"
          width="66.111"
          height="66.111"
          x="738.444"
          y="500.445"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="7.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter50_f"
          width="27.222"
          height="27.222"
          x="757.889"
          y="519.89"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter51_f"
          width="195"
          height="195"
          x="669"
          y="508"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="32.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter52_f"
          width="66.111"
          height="66.111"
          x="733.444"
          y="572.445"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="7.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter53_f"
          width="27.222"
          height="27.222"
          x="752.889"
          y="591.889"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter54_f"
          width="20.163"
          height="89.442"
          x="736.419"
          y="519.279"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="3.361"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter55_f"
          width="6.836"
          height="45.324"
          x="743.082"
          y="541.338"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="0.776"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter56_f"
          width="2.815"
          height="10.512"
          x="745.093"
          y="558.744"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="0.517"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter57_f"
          width="35"
          height="35"
          x="784"
          y="572"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter58_f"
          width="11"
          height="11"
          x="796"
          y="584"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter59_f"
          width="5"
          height="5"
          x="799"
          y="587"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter60_f"
          width="33"
          height="33"
          x="715"
          y="597.999"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter61_f"
          width="9.889"
          height="9.889"
          x="726.555"
          y="609.555"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter62_f"
          width="4.778"
          height="4.778"
          x="729.111"
          y="612.11"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter63_f"
          width="33"
          height="33"
          x="593"
          y="514"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="6.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter64_f"
          width="9.889"
          height="9.889"
          x="604.556"
          y="525.556"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter65_f"
          width="4.778"
          height="4.778"
          x="607.111"
          y="528.112"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter66_f"
          width="17.878"
          height="66.877"
          x="665.061"
          y="534.061"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.969"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter67_f"
          width="6.074"
          height="33.297"
          x="670.963"
          y="550.851"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="0.685"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter68_f"
          width="2.494"
          height="7.938"
          x="672.753"
          y="563.53"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="0.457"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter69_f"
          width="37.721"
          height="9.721"
          x="641.639"
          y="562.639"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="1.68"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter70_f"
          width="18.773"
          height="3.218"
          x="651.113"
          y="565.891"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="0.388"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter71_f"
          width="4.478"
          height="1.367"
          x="658.261"
          y="566.816"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="0.259"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter72_f"
          width="15.163"
          height="67.263"
          x="739.537"
          y="534.945"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="2.527"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter73_f"
          width="5.141"
          height="34.085"
          x="744.548"
          y="551.534"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="0.583"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter74_f"
          width="2.117"
          height="7.906"
          x="746.061"
          y="564.624"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="0.389"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter75_f"
          width="195"
          height="195"
          x="701"
          y="425"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="32.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter76_f"
          width="66.111"
          height="66.111"
          x="765.445"
          y="489.445"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="7.5"
          ></feGaussianBlur>
        </filter>
        <filter
          id="automation_filter77_f"
          width="27.222"
          height="27.222"
          x="784.889"
          y="508.889"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur"
            stdDeviation="5"
          ></feGaussianBlur>
        </filter>
        <linearGradient
          id="automation_paint0_linear"
          x1="-13.907"
          x2="43.971"
          y1="32.822"
          y2="-12.561"
          gradientUnits="userSpaceOnUse"
        >
          <stop offset="0.385" stopColor="#352B73"></stop>
          <stop offset="1" stopColor="#F594FE" stopOpacity="0"></stop>
        </linearGradient>
        <radialGradient
          id="automation_paint1_radial"
          cx="0"
          cy="0"
          r="1"
          gradientTransform="matrix(14.13979 21.0186 -13.77081 9.264 959.579 746.63)"
          gradientUnits="userSpaceOnUse"
        >
          <stop stopColor="#F896FE"></stop>
          <stop offset="1" stopColor="#F896FE" stopOpacity="0"></stop>
        </radialGradient>
        <linearGradient
          id="automation_paint2_linear"
          x1="-15.464"
          x2="48.894"
          y1="36.496"
          y2="-13.968"
          gradientUnits="userSpaceOnUse"
        >
          <stop offset="0.385" stopColor="#352B73"></stop>
          <stop offset="1" stopColor="#F594FE" stopOpacity="0"></stop>
        </linearGradient>
        <radialGradient
          id="automation_paint3_radial"
          cx="0"
          cy="0"
          r="1"
          gradientTransform="rotate(-176.742 291.683 349.305) scale(44.3516 29.0579)"
          gradientUnits="userSpaceOnUse"
        >
          <stop stopColor="#F896FE"></stop>
          <stop offset="1" stopColor="#F896FE" stopOpacity="0"></stop>
        </radialGradient>
        <linearGradient
          id="automation_paint4_linear"
          x1="-25.636"
          x2="81.056"
          y1="60.504"
          y2="-23.155"
          gradientUnits="userSpaceOnUse"
        >
          <stop offset="0.385" stopColor="#352B73"></stop>
          <stop offset="1" stopColor="#F594FE" stopOpacity="0"></stop>
        </linearGradient>
        <radialGradient
          id="automation_paint5_radial"
          cx="0"
          cy="0"
          r="1"
          gradientTransform="matrix(-1.70647 -73.5062 48.15932 -1.11803 561.921 444.747)"
          gradientUnits="userSpaceOnUse"
        >
          <stop stopColor="#F896FE"></stop>
          <stop offset="1" stopColor="#F896FE" stopOpacity="0"></stop>
        </radialGradient>
        <clipPath id="automation_clip0">
          <path
            fill="#fff"
            d="M0 0H169.121V195H0z"
            transform="translate(626 490.001)"
          ></path>
        </clipPath>
      </defs>
    </svg>
  );
}

export default Section5SVG;