import arvrmrcss from './ar-vr-mr.module.css'
export default function Dots() {
    return (<div className={arvrmrcss.dots}>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>
        <div className={arvrmrcss.dot}><div className={arvrmrcss.dotinside}></div></div>

    </div>)
}